version: "3.3"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
        - '27017:27017'


  server:
    container_name: gateway_server
    restart: unless-stopped
    image: gateway_server-prod:1.0.0
    build: 
      context: server
      dockerfile: Dockerfile
       
    ports:
      - '5000:5000'
    depends_on:  
      - mongo


  client:
    container_name: gateway_client
    restart: unless-stopped
    image: gateway_client-prod:1.0.0
    build: 
      context: client
      dockerfile: Dockerfile
       
    ports:
      - '80:3000'
    
      
   
   

   


    

